### ISSUE TITLE
Puchase callback is leaking

### ISSUE THREAD

**Issue by TemMax** [apphud/ApphudSDK-Android#23]
Hi! When I use Apphud#purchase with success result and after close fragment I received that leak is happened. I thing that callback should be called when all internal operations is completed and my callback isn't need for billing client anymore.

**Comment by alex-soft-r** [comment]
Hello

Could you show which version of the SDK you are using, as well as give an example of the code that, in your opinion, leads to an this error.

**Comment by ren6** [comment]
Closed due to outdate
