### ISSUE TITLE
Не работает метод получения пейволов

### ISSUE THREAD

**Issue by uniqby** [apphud/ApphudSDK-Android#28]
```Kotlin
Apphud.getPaywalls { paywalls, error ->
    Log.d("DEBUG", error.toString()) // E/Apphud: Try invoke paywalls delayed callback
}
```

**Comment by alex-soft-r** [comment]
Если вы запускаете программу на эмуляторе, то убедитесь что там присутствуют сервисы Google Billing. 
Со своей стороны, мы настоятельно рекомендуем проверять всё что связано с покупками на реальных устройствах.
