### ISSUE TITLE
плохо работает проверка подписки

### ISSUE THREAD

**Issue by n00ner** [apphud/ApphudSDK-Android#9]
После успешной покупки внутри приложения (оплата реальной картой) метод hasActiveSubscription возвращает false.

**Comment by ren6** [comment]
Привет, видим проблему. Изучаем вопрос. Что-то не то с колбеками.

**Comment by ren6** [comment]
@n00ner проблема была исправлена в версии 0.8.5. Обновитесь, пожалуйста. Приносим извинения за неудобства.
